import type { Metadata } from "next";
import { Neuton } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { WppButton } from "./components/WppButton";

const neutonSans = Neuton({
  subsets: ["latin"],
  weight: ["200", "300", "400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${neutonSans} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <WppButton />
      </body>
    </html>
  );
}
